service: congress-stats

provider:
  name: aws
  runtime: nodejs6.10

functions:
  month:
    handler: handler.getMonthStats
    events:
      - http:
          path: congress-stats/year/{year}/month/{month}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                year: true
                month: true
    environment:
      PROPUBLICA_API_KEY: ${file(./env.yml):propublicaApiKey}
